[package]
name = "aoc2024"
version = "0.1.0"
edition = "2024"

[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "bench"
harness = false

[dependencies]
mimalloc = { version = "*", default-features = false }
